package adamrcarter.funfacts;

import java.util.Random;

/**
 * Created by adamcarter on 12/3/14.
 */
public class FactBook {

    public String[] mFacts = {

            "There is gravity in space — if there wasn't, stars and planets wouldn't be able to form.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Mammoths still walked the earth when the Great Pyramid was being built.",
            "Ants communicate with chemicals and can speak many phrases including to take cover from danger.",
            "New research suggests that dolphins are second only to humans in intelligence.",
            "Federal law once allowed the government to quarantine people who came in contact with aliens.",
            "Less than 7 out of every 100 people in the world have a college degree.",
            "The treaty of friendship between North Korea and China doesn't expire until 2021.",
            "Everyday, tens of thousands of Indian child-slaves mine mica – The little sparkles in women's makeup.",
            "The reason eyewitness testimonies can differ is because each person has other memories that can alter their view of the event in question.",
            "The Great Depression was so bad that Cameroon, a West African nation, sent New York $3.77 in hunger relief.",
            "\"The Dark Knight\" was the first Batman film with no live-action or CGI bats.",
            "Suicide is the leading cause of death among California gun purchasers.",
            "Fast food chain Arby's bought Pharrell Williams' hat from the 2014 Grammy Awards for $44,100.",
            "90% of U.S. dollar bills are contaminated with cocaine, according to studies.",
            "Mars is red because its surface is covered in iron oxide, which is the chemical that makes blood and rust look red.",
            "One slice of Godiva Chocolate Cheesecake from the Cheesecake Factory has 1,110 calories.",
            "The Lamborghini that Bruce Wayne drives in \"The Dark Knight\" is called the Murciélago, which is Spanish for bat.",
            "Nicolas Cage once bought a pet octopus because he thought it would make him a better actor.",
            "A woman once set her duplex on fire to kill a spider.",
            "A 5-minute shower in North America uses more water than is available in an entire day to a person living in the slum of a developing nation.",
            "People participate in Black Friday due to a misconception that there is a scarcity of items and deals.",
            "A relaxed state of mind and an influx of dopamine makes people more creative, which is why many people have good ideas in the shower.",
            "If the Earth was smooth, the ocean would cover the entire surface to a depth of 12,000 feet.",
            "Jay-Z has the second highest amount of number one albums of all time. The Beatles have the most.",
            "Only 5% of Twitter users have more than 100 followers.",
            "America has the highest number of serial killers in the world.",
            "The peak relationship breakup times are two weeks before Christmas and the beginning of March.",
            "It is estimated that in 1,000 years, our languages today will be extinct.",
            "The amount needed to feed every child for a year is less than 20% of the annual amount given to charity by the citizens of the USA.",
            "If two people never stop loving each other, one will have to watch the other die.",
            "About a quarter of the world’s hazelnuts (nearly 100,000 tons a year) are used to make Nutella.",
            "Oxford University is older than the Aztec Empire.",
            "Iron Man's computer, J.A.R.V.I.S., is an acronym for \"Just A Rather Very Intelligent System.\"",
            "If you drilled a tunnel through the Earth and jumped in, it would take you about 42-53 minutes to get to the other side.",
            "Jupiter shields Earth from hundreds of asteroids heading towards our planet.",
            "Rubbing a banana peel on a mosquito bite can help stop the itching.",
            "Approximately 49 moons could fit into Earth.",
            "The U.S. has a greater percentage of its population in jail than any other country in the world.",
            "\"Almost\" is the longest word in the English language with all the letters in alphabetical order.",
            "A study conducted by GE Money states that women spend more than 8 years of their life shopping.",
            "Our brains are wired to prefer music we already know.",
            "In Ancient Greek, the word \"idiot\" was used to describe any person who was not interested in politics.",
            "About 80% of the animals found in Madagascar do not exist anywhere else on Earth.",
            "Every 24 hours, about 8,640,000 lightning bolts touch the earth.",
            "Research has suggested that yoga improves social and occupational functioning in schizophrenic patients.",
            "Americans eat approximately 100 acres of pizza each day, or 350 slices per second.",
            "Putting sugar on a wound or cut will greatly reduce pain and speed up the healing process.",
            "Jupiter weights more than twice as much as all our other planets together.",
            "According to research, the deadliest holidays in the U.S. are 4th of July, Christmas, and New Year's Day.",
            "Playing Tetris soon after a traumatic experience has been proven to help wipe bad memories and prevent flashbacks.",
            "The average American Thanksgiving dinner is 2,536 calories — assuming that you have normal portions and don't go back for seconds.",
            "Dogs actually listen to and mull over human words to decipher what we're saying to them.",
            "Cats can learn how to bark from listening to dogs.",
            "Heading a soccer ball causes mild concussions, and players that head the ball often have low cognitive performance.",
            "There are fewer than 900 mountain gorillas left in the world, due to poaching, habitat loss and disease.",
            "Of the Seven Wonders of the World, 3 fell due to earthquakes, 2 due to fires, 1 probably never existed, and only one stands today.",
            "A man once ordered a TV on Amazon, but got a semi-automatic assault rifle instead.",
            "84% of vegetarians and vegans switch back to eating meat at some point.",
            "Studying for 30-50 minutes, with 10 minute breaks is one of the best methods to improve your retention.",
            "A live flu virus can last up to 17 days on a dollar bill.",
            "The arms of condemned prisoners are swabbed with alcohol prior to lethal injection in order to keep the area sterile.",
            "William Shatner could never spread his fingers for the Vulcan greeting unless the studio crew tied fishing line around his fingers.",
            "NASA estimates that the value of minerals in the asteroid belt exceeds $600,000,000,000,000,000,000.",
            "A microwave uses more electricity to power its clock than it does to heat your food.",
            "Ten years ago, a 1GB SD card was $500.",
            "Earth is the only planet not named after a god.",
            "Armadillos have four babies at the same time, and they are always the same sex.",
            "An octopus will eat its own arms if it gets really hungry.",
            "Dolphins sleep with only half of their brain at a time, and with one eye open.",
            "Russian scientists revived a plant from a fossilized fruit trapped in ice 32,000 years ago, burred by an Artic Squirrel.",
            "90% of the foods we consume come from just 30 plants.",
            "When asked what his IQ was, Stephen Hawking replied “I have no idea. People who boast about their IQ are losers”",
            "Your odds of dying in a car accident are around 1 in 5,000.",
            "Indoor tanning has caused more cases of skin cancer, than smoking has caused cases of lung cancer.",
            "We live about 80 milliseconds in the past because that's how long it takes our brains to process information.",
            "Napping for just 6 minutes can help improve your memory.",
            "Dogs tilt their heads when something piques their interest and they want to hear better.",
            "Cleaning can help with depression.",
            "Creative-type people are more inclined to sleep on their left side.",
            "Instead of saying you have to do something, tell yourself that you get to do it and you'll feel more empowered.",
            "Pumping your fists and shouting, \"Yeah!\" when you first get woken up by the alarm will help you get out of bed faster.",
            "In a group setting, people tend to automatically look at the person they feel the closest to when a group laughs.",
            "If you refer to people by their names (instead of he/she), it establishes a sense of trust and friendship.",
            "Asking for small favors from people can make you more likable.",
            "If you act happy and excited when you first meet people, they will act the same way toward you.",
            "If you're feeling nervous, start chewing gum, your brain will reason that you're not in danger because you would not be eating if you were.",
            "If you place a mirror facing angry customers, they tend to act more rational.",
            "Research concludes doing things that scare you will make you happier.",
            "A new study has been released that theoretically proves the possibility of time travel.",
            "Studies have found that sporting the latest technology makes you look like more of a leader.",
            "Eldest sisters tend to be the most ambitious and successful.",
            "The Aztecs killed about 20,000 people every year to please the gods.",
            "Blood from a younger person may be able to heal older brains from diseases like Alzheimer's.",
            "Cuddling releases oxytocin – A chemical that can heal wounds and relieve pain.",
            "About 15,000 new animal species are found every year.",
            "The structure of your brain changes every time you learn something new.",
            "Assuming Rudolph is in front, the number of possible way to arrange Santa\'s other eight reindeer is 40,320.",
            "Divide your weight by six to get the approximate number of quarts of blood in your body.",
            "A rat can go without water longer than a camel can.",
            "The Monongahela River\'s name translated into English means \"high banks breaking off and falling down in places.\"",
            "The most common name in the world is Mohammed.",
            "Hummingbirds are the only animal that can fly backwards.",
            "During his life time, the average male eats 50 tons of food.",
            "Hydroxydesoxycorticosterone and hydroxydeoxycorticosterones are the largest anagrams.",
            "The average person falls asleep in seven minutes.",
            "Canada is an Indian word meaning \"Big Village.\"",
            "It was discovered on a space mission that a frog can throw up. The frog throws up it\'s stomach first, so the stomach is dangling out of it\'s mouth. Then the frog uses it\'s forearms to dig out all of the stomach\'s contents and then swallows the stomach back down again.",
            "The human body contains enough fat to make seven bars of soap and enough iron to make a single one inch nail.",
            "Most heart attacks occur between 6:00 a.m. and noon when blood pressure naturally rises.",
            "Twenty-six astronauts have reported seeing UFOs while in orbit around the Earth.",
            "Fingernails grow four times faster than toenails--about two hundredths of an inch per week.",
            "Dr. Samuel A. Mudd was the physician who set the leg of",
            "Lincoln\'s assassin John Wilkes Booth...and whose shame created the expression for ignominy, \"His name is Mudd.\"",
            "Playing cards were issued to British pilots in WWII. If captured, they could be soaked in water and unfolded to reveal a map for escape.",
            "Your brain uses 10 times more oxygen than the rest of your body.",
            "Because the eyes work harder when viewing objects up close, particularly on a computer monitor, it is the proximity of the VDT screen to the eyes that causes eyestrain, not \"radiation\" emitted from the screen.",
            "\"I am\" is the shortest complete sentence in the English language.",
            "Most precious gems are actually colorless. Their color comes from impurities in the stone than act as pigmenting agents.",
            "Gordon Sumner, the rock star and actor known as Sting, got his nickname from the yellow-and-black jerseys he used to wear, which fellow musicians thought made him look like a bumble bee.",
            "A lightning bolt heats the air around it to three times the temperature of the sun\'s surface.",
            "For every shark that takes a bite out of a human being, humans kill about a million sharks.",
            "Ben and Jerry\'s send the waste from making ice cream to local pig farmers to use as feed. Pigs love the stuff, except for one flavor: Mint Oreo.",
            "They live an average of 77 years and have the longest lifespan in the United States - nuns.",
            "Wilma Flintstone\'s maiden name was Wilma Slaghoopal, and Betty Rubble\'s Maiden name was Betty Jean Mcbricker.",
            "A giant squid\'s eye is the largest of any animal\'s, exceeding 15 inches in diameter.",
            "The shoestring was invented in England in 1790. Prior to this time, all shoes were fastened with buckles.",
            "The state of Kansas once passed legislation rounding off the value of Pi from 3.14159265...to an even 3.",
            "The life span of a taste bud is ten days.",
            "Gymnastics is the only sport more popular with women than with men.",
            "In 1879 a drug was introduced to treat morphine addiction. The drug: cocaine.",
            "The characters Bert and Ernie on Sesame Street were named after Bert the cop and Ernie the taxi driver in Frank Capra\'s \"Its A Wonderful Life\"",
            "Research indicates that mosquitoes are attracted to people who have recently eaten bananas.",
            "Mosquitoes are attracted to the colour blue.",
            "Studies show that if a cat falls off the seventh floor of a building it has about thirty percent less chance of surviving than a cat that falls off the twentieth floor. It supposedly takes about eight floors for the cat to realize what is occurring, relax and correct itself.",
            "If you toss a penny 10,000 times, it will not be heads 5000 times, but more like 4950. The heads picture weighs more, so it ends up on the bottom.",
            "If your eyes are six feet above the surface of the ocean, the horizon will be about three statute miles away.",
            "Alaska has the highest percentage of Baby Boomers; Utah the lowest.",
            "If NASA sent birds into space they would soon die, they need gravity to swallow.",
            "Armored knights raised their visors to identify themselves when they rode past their king. This custom has become the modern military salute.",
            "Every time you lick a stamp, you\'re consuming 1/10 of a calorie.",
            "On average, an adult laughs about 15 times a day; a child laughs 400 times.",
            "In medieval England beer was often served with breakfast.",
            "The lens of the eye continues to grow throughout a person\'s life.",
            "The Atlantic Ocean is saltier than the Pacific Ocean.",
            "The telephone area code for a cruise ship in the Atlantic Ocean is 871.",
            "There are more stars in the universe, than grains of sand on all the beaches in the world.",
            "On the day that \"The Wizard of Oz\'s\" Judy Garland died, a tornado touched down in Kansas.",
            "If a statue in the park of a person on a horse has both front legs in the air, the person died in battle; if the horse has one front leg in the air, the person died as a result of wounds received in battle; if the horse has all four legs on the ground, the person died of natural causes.",
            "\"111,111,111 x 111,111,111 = 12,345,678,987,654,321\"",
            "The glue on Israeli postage stamps is certified kosher.",
            "The bones of a pigeon weigh less than its feathers.",
            "At 90 degrees (F) below zero your breath will freeze in midair and fall to the ground.",
            "The average person is about a quarter of an inch taller at night.",
            "A pregnant goldfish is called a twit.",
            "Charles Lindbergh took only four sandwiches with him on his famous transatlantic flight.",
            "3000 cows are needed to supply the leather for a year\'s supply of NFL footballs.",
            "If there were ever an ocean big enough, Saturn would be the only planet that could float.",
            "Al Capone\'s business card said he was a used furniture dealer.",
            "The Hewlett Packard computer company\'s first product was an automatic urinal flusher.",
            "All the coal, oil, gas, and wood on Earth would only keep the Sun burning for a few days.",
            "A group of rhinos is called a crash.",
            "Bank robber John Dillinger played professional baseball.",
            "At Old English weddings, guests threw shoes at the groom.",
            "Only one person in two billion will live to be 116 or older.",
            "The longest recorded flight of a chicken is thirteen seconds.",
            "Your hearing is not as sharp on a full stomach.",
            "The last United States train robbery took place in 1933.",
            "A 1,200 pound horse eats about 15 lbs. of hay and nine pounds of grain everyday (seven times its own weight each year).",
            "Albert Einstein didn\'t talk until he was four years old.",
            "Einstein couldn\'t read until the age of nine.",
            "The two lines that connect the bottom of your nose to your lip are called the philtrum.",
            "Your stomach has to produce a new layer of mucus every two weeks otherwise it will digest itself.",
            "1/100th of a second is called a \"jiffy\".",
            "A group of kangaroos is called a mob.",
            "The housefly hums in the middle octave, key of F.",
            "\"J\", the youngest letter in the English alphabet, was not added until the 1600s.",
            "It takes around 200,000 frowns to create a permanent brow line.",
            "The Baby Ruth candy bar was actually named after Grover Cleveland\'s baby daughter, Ruth.",
            "The fastest-moving land snail is the common qarden snail whose top speed is 55 yards per hour or 0.0313 mph.",
            "The most common time to sight a UFO is 11pm.",
            "There are 31,557,600 seconds in a year.",
            "The right lung takes in more air than the left.",
            "On average, Americans buy 1.5 toothbrushes a year.",
            "60% of the swimsuits sold in the U.S. never get wet.",
            "It takes about 30 minutes for an aspirin to find a headache.",
            "In Nepal, Mt. Everest is known as \"Gauriosankar\".",
            "Los Angeles Police Department ballistics experts say that the fastest bullet is fired from a .223 caliber rifle and travels at 3,500 feet per second, more than 3 times the speed of sound.",
            "If an octopus is hungry enough, it will eat its own arms.",
            "The knee-high measurement of an average-sized grasshopper is about 1/2 inch.",
            "An ostrich\'s eye is bigger than it\'s brain.",
            "A group of cows, twelve or more, are known as a \"flink.\"",
            "In a survey of 5,000 U.S. nurses, 40 percent said they would not recommend the medical facility where they worked to a relative.",
            "The ancient Romans died their hair with bird droppings.",
            "Only pharoahs were allowed to eat mushrooms in ancient Egypt.",
            "What area of your body has the most bacteria? Between your toes.",
            "Jimmy Carter was the first U.S. president to have been born in a hospital.",
            "Ratio of inductees into the Rock and Roll Hall of Fame who are hearing impaired: 3 in 5.",
            "The Yo-yo is believed to be the second-oldest toy in the world after dolls. The Greeks played with yo-yos as far back as 500 B.C.",
            "You use 15 different muscles in your face to laugh.",
            "The Sanskrit word for \"war\" means \"desire for more cows.\"",
            "A group of ravens is called a murder.",
            "Cleo and Caesar were the early stage names of Cher and Sonny Bono.",
            "Only about half of all spiders spin webs.",
            "Kangaroos are lactose-intolerant.",
            "Charles Darwin\'s cousin invented the IQ test.",
            "Goats can\'t legally wear trousers in Massachusetts.",
            "Niagara Falls was created by a glacier.",
            "Abraham Lincoln hated being called \"Abe\".",
            "Abe Lincoln\'s favorite sport was wrestling.",
            "5% of Americans let their dishes pile up for a couple of days before washing them.",
            "Clams can live as long as 150 years.",
            "In ancient China, doctors received their fees only if their patients were kept healthy. If the patient\'s health failed, the doctor sometimes paid the patient.",
            "It\'s illegal to ride an ugly horse down the street in Wilbur, Washington.",
            "The skin on your eyelid is one one-thousandth of an inch deep (the thinnest); the skin on your back is one-fifth of an inch (the thickest).",
            "According to research, you\'ll blow your nose about 250 times this year.",
            "Cows can be identified by noseprints.",
            "There are 2,598,960 possible hands in a five-card poker game.",
            "A group of frogs is called an army.",
            "101 Dalmatians and Peter Pan (Wendy) are the only two",
            "Disney cartoon features with both parents are present and don\'t die throughout the entire movie.",
            "An electric eel\'s charge is so potent it can knock a horse unconscious from twenty feet away.",
            "70% of house dust consists of human skin.",
            "Artichokes are flowers.",
            "Elephants breathe 12 times a minute.",
            "It\'s impossible to snore in the weightlessness of space.",
            "Mosquitos have 47 teeth.",
            "An ecstatically weeping woman paid $8,625 at an auction for a pair of horseshoes worn by Mr. Ed.",
            "Mel Blanc (the voice of Bugs Bunny) was allergic to carrots. (Right, Shair?)",
            "The first tennis balls were stuffed with human hair.",
            "The average blink of an eye lasts one-tenth of a second.",
            "The average American uses 12 gallons of water while showering.",
            "In the Middle Ages, you were supposed to throw eggs at the bride and groom.",
            "In Lawrence, Kansas, it\'s against the law to carry bees around in your hat on city streets.",
            "According to the Consumer Product Safety Commission, the number of injuries caused by plug-in air fresheners is 1,823.",
            "\"Stewardesses\" is the longest word that is typed with only the left hand.",
            "In England, the Speaker of the House is not allowed to speak.",
            "Tomato ketchup was once sold in the U.S. as a medicine.",
            "Snakes can get malaria.",
            "Only 30% of humans can flare their nostrils.",
            "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
            "Ducks can get the flu.",
            "Siberia means \"sleeping land.\"",
            "In the Leaning Tower of Pisa, 6 of the tower\'s eight floors are without safety rails. More than 250 people have fallen to their deaths since 1174.",
            "Rubber bands last longer when refrigerated.",
            "There are 293 ways to make change for a dollar.",
            "There are more chickens than people in the world.",
            "The longest one-syllable word in the English language is \"screeched.\"",
            "On a Canadian two dollar bill, the flag flying over the Parliament Building is an American flag.",
            "All of the clocks in the movie \"Pulp Fiction\" are stuck on 4:20.",
            "No word in the English language rhymes with month, orange, silver or purple.",
            "\"Dreamt\" is the only English word that ends in the letters \"mt.\"",
            "Maine is the only state whose name is just one syllable.",
            "There are only four words in the English language which end in \"-dous\": tremendous, horrendous, stupendous, and hazardous.",
            "Los Angeles\'s full name is \"El Pueblo de Nuestra Senora la Reina de los Angeles de Porciuncula\"--and can be abbreviated to 3.63% of its size: \"L.A.\"",
            "A cat has 32 muscles in each ear.",
            "The only real person to be a Pez head was Betsy Ross.",
            "When the University of Nebraska Cornhuskers play football at home, the stadium becomes the state\'s third largest city.",
            "A dragonfly has a life span of 24 hours.",
            "A goldfish has a memory span of three seconds.",
            "A dime has 118 ridges around the edge.",
            "On an American one-dollar bill, there is an owl in the upper left-hand corner of the \"1\" encased in the \"shield\" and a spider hidden in the front upper right-hand corner.",
            "It\'s impossible to sneeze with your eyes open.(DON\'T try this @ home!)",
            "Mr.Rogers is an ordained minister.",
            "A golden razor removed from King Tut\'s Tomb was still sharp enough to be used.",
            "Abdul Kassam Ismael, Grand Vizier of Persia in the tenth century, carried his library with him wherever he went. The 117,000 volumes were carried by 400 camels trained to walk in alphabetical order.",
            "According to the Encyclopedia Britannica, 11th Edition, from 1910-1911, the word toast was borrowed from the Old",
            "French toste, which has the Latin root of torrere, tostum, meaning to scorch or burn.",
            "Acting was once considered evil, and actors in the first English play to be performed in America were arrested.",
            "All of the officers in the Confederate army were given copies of Les Miserables, by Victor Hugo, to carry with them at all times. Robert E. Lee, among others, believed that the book symbolized their cause. Both revolts were defeated.",
            "All office seekers in the Roman empire were obliged to wear a certain white toga for a period of one year before the election.",
            "At the turn of the last millennium, Dublin Ireland had the largest slave market in the world, run by the Vikings.",
            "Aztec emperor Montezuma had a nephew, Cuitlahac, whose name meant plenty of excrement.",
            "Before the 1800\'s there were no separately designed shoes for right and left feet.",
            "Czar Paul I banished soldiers to Siberia for marching out of step.",
            "Dog Days: Days of great heat. The Romans called the hottest weeks of summer canculares dies. Their theory was that the",
            "Dog Star (Sirius) rising with the sun, added to its heat and the dog-days (about July 3 to August 11) bore the combined heat of both.",
            "During 18th century France, visitors to the royal palace in Versailles were allowed to stand in a roped-off section of the main dining room and watch the king and queen eat.",
            "During the Cambrian period, about 500 million years ago, a day was only 20.6 hours long.",
            "During the Depression, banks first used Scotch tape to mend torn currency.",
            "During the eighteenth century, books that were considered offensive were sometimes punished by being whipped.",
            "Everyone believed in the Middle Ages--as Aristotle had--that the heart was the seat of intelligence.",
            "Evidence of shoemaking exists as early as 10,000 B.C.",
            "Francis Scott Key was a young lawyer who wrote the poem \'The Star Spangled Banner\' after being inspired by watching the Americans fight off the British attack of Baltimore during the War of 1812. The poem became the words to the national anthem.",
            "High-wire acts have been enjoyed since the time of the ancient Greeks and Romans. Antique medals have been excavated from Greek islands depicting men ascending inclined cords and walking across ropes stretched between cliffs. The Greeks called these high-wire performers neurobates or oribates. In the Roman city of Herculaneum there is a fresco representing an aerialist high on a rope, dancing and playing a flute. Sometimes Roman tightrope walkers stretched cables between the tops of two neighboring hills and performed comic dances and pantomimes while crossing.",
            "If a family had 2 servants or less in the U.S. in 1900, census takers recorded it as lower middle-class.",
            "If we had the same mortality rate as in the 1900s, more than half the people in the world today would not be alive.",
            "If you were born in Los Alamos, New Mexico during the Manhattan project (where they made the atomic bomb), your birth place is listed as a post office box in Albequerque.",
            "In 1778, fashionable women of Paris never went out in blustery weather without a lightning rod attached to their hats.",
            "In ancient Egypt, killing a cat was a crime punishable by death.",
            "In certain parts of India and ancient China, mouse meat was considered a delicacy.",
            "In midieval England, beer often was served with breakfast.",
            "In the 1700\'s, you could purchase insurance against going to hell, in London, England.",
            "In the 19th century, the British Navy attempted to dispel the superstition that Friday was an unlucky day to embark on a ship. The keel of a new ship was laid on a Friday, she was named H.M.S Friday, commanded by a Captain Friday, and finlly went to sea on a Friday. Neither the ship nor her crew were ever heard of again.",
            "In the Great Fire of London in 1666, half of London was burnt down but only six people were injured.",
            "In the marriage ceremony of the ancient Inca Indians of Peru, the couple was considered officially wed when they took off their sandals and handed them to each other.",
            "In Turkey, in the sixteenth and seventeenth centuries, anyone caught drinking coffee was put to death.",
            "In Victorian times, there was an intense fear of being buried alive, so when someone died, a small hole was dug from the casket to the surface, then a string was tied around the dead persons finger which was then attached to a small but loud bell that was hung on the surface of the grave, so then if someone was buried alive, they could ring the bell and whomever was on duty would go and dig them up. Someone was on the clock 24 hours a day- hence the grave yard shift.",
            "Income tax was first introduced in England in 1799 by British Prime Minister, William Pitt.",
            "It cost more to buy a car today in the United States than it cost Christopher Columbus to equip and undertake three voyages to the New World.",
            "It has been calculated that in the last 3,500 years, there have only been 230 years of peace throughout the civilized world.",
            "January is National Soup month.",
            "Native Americans never actually ate turkey; killing such a timid bird was thought to indicate laziness.",
            "53,312 inmate lawsuits were filed nationwide in 1995.",
            "A Virginia law requires all bathtubs to be kept out in the yards, not inside the house.",
            "According to British law passed in 1845, attempting to commit suicide was a capital offense. Offenders could be hanged for trying.",
            "Christmas was once illegal in England.",
            "George Washington is the only man whose birthday is a legal holiday in every state of the U.S as of a few years ago.",
            "Impotence is legal grounds for divorce in 24 American states.",
            "In a tradition dating to the begining of the Westminster system of government, the bench in the middle of a Westminster parliarment is two and a half sword lengths long. This was so the government and oppositon couldn\'t have a go at each other if it all got a bit heated",
            "In Alaska it is illegal to shoot at a moose from the window of an aeroplane or other flying vehicle.",
            "In Baltimore USA it is illegal to wash or scrub a sink regardless of how dirty it is.",
            "In Cleveland, Ohio it is illegal to catch mice without a hunting license.",
            "In England during Queen Victoria\'s reign, it was illegal to be a homosexual but not a lesbian. The reason being that when the Queen was approving the law she wouldn\'t believe that women would do that.",
            "In Hartford, Connecticut, it is illegal for a husband to kiss his wife on Sundays.",
            "In Italy, it is illegal to make coffins out of anything except nutshells or wood.",
            "In Jasmine, Saskatchewan, it is illegal for a cow to moo within 300 km of a private home.",
            "In Kentucky, it is illegal to carry ice-cream in your back pocket.",
            "In Texas, it is illegal to put graffiti on someone else\'s cow.",
            "In the UK, there is no act of parliament making it illegal to commit murder. Murder is only illegal due to legal precedent.",
            "It is illegal to eat oranges while bathing in California.",
            "It is illegal to frown at cows in Bladworth, Saskatchewan.",
            "It is illegal to hunt camels in the state of Arizona.",
            "It was once against the law to have a pet dog in a city in Iceland.",
            "It was once against the law to slam your car door in a city in Switzerland.",
            "Mailing an entire building has been illegal in the U.S. since 1916 when a man mailed a 40,000-ton brick house across Utah to avoid high freight rates.",
            "Pennsylvania was the first colony to legalize witchcraft.",
            "107 incorrect medical procedures will be performed by the end of the day today.",
            "A Boeing 747\'s wingspan is longer than the Wright brother\'s first flight.",
            "A bolt of lighting can strike the earth with a force as great as 100 million volts.",
            "A cesium atom in an atomic clock beats 9,192,631,770 times a second.",
            "A creep is a metallurgical term for when something that is normally very strong bends because of gravity. This happens to many metals at high temperatures, where they won\'t melt but they will creep.",
            "A cubic mile of fog is made up of less than a gallon of water.",
            "A device invented as a primitive steam engine by the Greek engineer Hero, about the time of the birth of Christ, is used today as a rotating lawn sprinkler.",
            "A downburst is a downward blowing wind that sometimes comes blasting out of a thunderstorm. The damage looks like tornado damage, since the wind can be as strong as an F2 tornado, but debris is blown straight away from a point on the ground. It\'s not lifted into the air and transported downwind.",
            "A fierce gust of wind blew 45 year old Vittorio Luise\'s car into a rover near Naples, Italy, in 1980. He managed to break a window, climb out and swim to shore--where a tree blew over and killed him.",
            "A full loaded supertanker traveling at normal speed takes at least twenty minutes to stop.",
            "A full moon always rises at sunset.",
            "A full moon is nine times brighter than a half moon.",
            "A jumbo jet uses 4,000 gallons of fuel to take off.",
            "A large flawless emerald is worth more than a similarly large flawless diamond.",
            "A lightning bolt generates temperatures five times hotter than those found on the sun\'s surface.",
            "A manned rocket reaches the moon in less time than it took a stagecoach to travel the length of England.",
            "A normal raindrop falls at about 7 miles per hour.",
            "A penny whistle has six finger holes.",
            "A rainbow can only occur when the sun is 40 degrees or less above the horizon.",
            "A silicon chip a quarter-inch square has the capacity of the original 1949 ENIAC computer, which occupied a city block.",
            "A standard grave is 7\'8 x 3\'2 x 6.",
            "A syzygy occurs when three atronomical bodies line up.",
            "A two-bit moon is in its first quarter.",
            "A wind with a speed of 74 miles or more is designated a hurricane.",
            "About seven million cars are junked each year in the U.S.",
            "According to the Gemological Institute of America, up until 1896, India was the only source for diamonds to the world.",
            "According to the Texas Department of Transportation, one person is killed annually painting stripes on the state\'s highways and roads.",
            "All snow crystals are hexagonal.",
            "All the gold produced in the past five hundred years, if melted, could be compressed into a 50-foot cube.",
            "All totalled, the sunlight that strikes Earth at any given moment weighs as much as an ocean liner.",
            "American Airlines saved $40,000 in 1987 by eliminating one olive from each salad served in first class.",
            "An enneahedron is solid with nine faces.",
            "An inch of snow falling evenly on one acre of ground is equivalent to about 2715 gallons of water.",
            "Any free moving liquid in outer space will form itself into a sphere because of its surface tension.",
            "Approximately 98% of software in China is pirated.",
            "April is Earthquake Preparedness month. For a little added incentive, consider this- The most powerful earthquake to strike the United States occurred in 1811 in New Madrid, Missouri. The quake shook more than one million square miles, and was felt as far as 1,000 miles away.",
            "At any given time, there are 1,800 thunderstorms in progress over the earth\'s atmosphere.",
            "At room temperature, the average air molecule travels at the speed of a rifle bullet.",
            "Back in the mid to late 80\'s, an IBM compatible computer wasn\'t considered a hundred percent compatible unless it could run Microsoft\'s Flight Simulator.",
            "Bacteria, the tiniest free-living cells, are so small that a single drop of liquid contains as many as 50 million of them.",
            "Bamboo (the world\'s tallest grass) can grow up to 90 cm in a day.",
            "Because of the rotation of the earth, an object can be thrown farther if it is thrown west.",
            "Carolyn Shoemaker has discovered 32 comets and approximately 300 asteroids.",
            "Clouds fly higher during the day than the night.",
            "Construction workers hard hats were first invented and used in the building of the Hoover Dam in 1933.",
            "Did you know you share a birthday with at least nine other million people in the world?",
            "During the time that the atomic bomb was being hatched by the United States at Alamogordo, New Mexico, applicants for routine jobs like janitors, were disqualified if they could read. Illiteracy was a job requirement. The reason: the authorities did not want their trash or other papers read.",
            "Each year there is one ton of cement poured for each man, woman and child in the world.",
            "Ethernet is a registered trademark of Xerox, Unix is a registered trademark of AT&T.",
            "Experts at Intel say that microprocessor speed will double every 18 months for at least 10 years.",
            "February 1865 is the only month in recorded history not have a full moon.",
            "If you attempted to count the stars in a galaxy at a rate of one every second it would take around 3,000 years to count them all.",
            "If you yelled for 8 years, 7 months and six days, you would have produced enough sound energy to heat one cup of coffee.",
            "In 1949, forecasting the relentless march of science, Popular Mechanics said computers in the future may weigh no more than 5 tons.",
            "In 1961, MIT student Steve Russell, created SPACEWARS, the first interactive computer game, on a Digital PDP-1 (Programmed Data Processor-1) mainframe computer. Limited by the computer technology of the time, ASCII text characters were the \'graphics\' and people could only play the game on a device that took up the floorspace of a small house.",
            "Iron nails cannot be used in aok because the acid in the wood corrodes them.",
            "It takes 8.5 minutes for light to get from the sun to earth.",
            "It takes one fifteen-to-twenty-year-old tree to produce seven hundred paper grocery bags.",
            "It takes the insect-eating Venus Flytrap plant only half a second to shut its trap on its prey.",
            "Methane gas can often be seen bubbling up from the bottom of ponds. It is produced by the decomposition of dead plants and animals in the mud.",
            "The Venus\'s flytrap can eat a whole cheeseburger.",
            "4,000 people are injured by tea pots every year.",
            "A 60-minute cassette contains 565 feet of tape.",
            "A coat hanger is forty-four inches long if straightened.",
            "A dime has 118 ridges around the edge.",
            "A good typist can strike twenty keys in a second.",
            "A person uses more household energy shaving with a hand razor at a sink (because of the water power, the water pump and so on) than he would by using an electric razor.",
            "A quarter has 119 grooves on its edge, a dime has one less groove.",
            "A toothpick is the object most often choked on by Americans",
            "A typical double mattress contains as many as two million house dust mites.",
            "A wedding ring is generally exempt by law from inclusion among the assets in a bankruptcy estate. That means that a wedding ring can\'t be seized by creditors, no matter how much the bankrupt person owes.",
            "According to a market research survey done some time ago, 68% of consumers receiving junk mail actually open the envelopes.",
            "According to one study, 24% of lawns have some sort of lawn ornament.",
            "All hospitals in Singapore use Pampers diapers.",
            "Aluminum is strong enough to support 90,000 pounds per square inch.",
            "An average of 200 million credit cards are used every day in the United States.",
            "Approximately 30 billion cakes of Ivory Soap had been manufactured by 1990.",
            "As of 1983, an average of three billion Christmas cards were sent annually in the United States.",
            "At the height of inflation in Germany in the early 1920s, one U.S. dollar was equal to 4 quintillion German marks.",
            "Avery Laser Labels are named after company founder R. Stanton Avery.",
            "Colgate faced a big obstacle marketing toothpaste in Spanish speaking countries. Colgate translates into the command \"go hang yourself.\"",
            "Each king in a deck of playing cards represents a great king from history. Spades - King David; Clubs - Alexander the Great; Hearts - Charlemagne; and Diamonds - Julius Caesar.",
            "Each of the suits on a deck of cards represents the four major pillars of the economy in the middle ages: heart represented the Church, spades represented the military, clubs represented agriculture, and diamonds represented the merchant class.",
            "Each of us generate 5 pounds of rubbish a day; most of it is paper.",
            "Every year, over 8,800 people injure themselves with a toothpick.",
            "Hallmark makes cards for 105 different relationships.",
            "How valuable is the penny you found laying on the ground?",
            "If it takes just a second to pick it up a person could make $36.00 per hour just picking up pennies.",
            "If done perfectly, any rubix cube combination can be solved in 17 turns.",
            "If you lace your shoes from the inside to the outside, the fit will be snugger around your big toe.",
            "In 1990, there were about 15,000 vacuum cleaner related accidents in the U.S.",
            "In 75% of American households, women manage the money and pay the bills.",
            "In every deck of cards, the King of Hearts is sticking his sword through his head. That\'s why he\'s often called the Suicide King.",
            "In historic Deerfield, Massachusetts a guide was showing us fireplaces and some old cooking items. One of the items was an iron standing grid that they would slide bread slices into and place in front of the fire. This grid could turn around and the story goes that the women would push it with their toe; originating the term toe stir which eventually became toaster.",
            "In order for a deck of cards to be mixed up enough to play with properly, it should be shuffled at least seven times.",
            "It\'s rumored that sucking on a copper penny will cause a breathalyzer to read 0.",
            "Ivory bar soap floating was a mistake. They had been mixing the soap formula causing excess air bubbles that made it float. Customers wrote and told how much they loved that it floated, and it has floated ever since.",
            "John F. Kennedy\'s rocking chair was auctioned off for $442,000.",
            "Ketchup is excellent for cleaning brass, especially tarnished or corroded brass.",
            "Kleenex tissues were originally used as filters in gas masks.",
            "Mosquito repellants do not repel. They hide you. The spray blocks the mosquito\'s sensors so they do not know you are there.",
            "Murphy\'s Oil Soap is the chemical most commonly used to clean elephants.",
            "On average, there are 333 squares of toilet paper on a roll.",
            "The first U.S. coin to bear the words, United States of America was a penny made in 1727. It was also inscribed with the plain-spoken motto: Mind your own business."

    };

    public String getFact() {


    String fact = "";

    // Randomly select a fact
    Random randomGenerator = new Random(); // construct a new random number generator
    int randomNumber = randomGenerator.nextInt(mFacts.length);

    fact = mFacts[randomNumber];

        return fact;
    }
}